# Configuration for solana-validator-ha binary to use with mock server
validator:
  name: validator-1
  rpc_url: http://localhost:8989/validator-1-rpc
  public_ip_service_urls:
    - http://localhost:8989/validator-1/public-ip
  identities:
    passive_pubkey: CP6FdV1zoaB64zV7riBPcMNV4WrtH6NZqEcN8cR1yp3i

cluster:
  name: mainnet-beta
  rpc_urls:
    - http://localhost:8989/solana-network-rpc

prometheus:
  port: 9091

failover:
  active:
    command: ../set-identity.sh
    args: ["1", active]
  passive:
    command: ./restart-validator-as.sh
    args: [passive]
profiles:
  main:
    priority: 0
    identities:
      active_pubkey: 7TCCEYMNjpRRdVQiMMYkNWJ9ECVThcUaw8mp11AWhTKe
    vote_pubkey: 7TCCEYMNjpRRdVQiMMYkNWJ9ECVThcUaw8mp11AWhTKe
    authorized_voter: 7TCCEYMNjpRRdVQiMMYkNWJ9ECVThcUaw8mp11AWhTKe
    peers:
      validator-1:
        ip: 192.168.1.101
      validator-2:
        ip: 192.168.1.102
      validator-3:
        ip: 192.168.1.103
