validator:
  name: "validator-2"
  rpc_url: "http://mock-solana:8899?validator=validator-2"
  public_ip_service_urls: ["http://mock-solana:8899/public-ip"]
  identities:
    passive_pubkey: "DJ7w4p8Ve7qdSAmkpA3sviSbsd1HPUxd43x7MTH72JHT"

cluster:
  name: "mainnet-beta"
  rpc_urls: ["http://mock-cluster:8899"]

prometheus:
  port: 9090
  static_labels:
    environment: "shared-backup-integration-test"
    validator: "validator-2"

failover:
  poll_interval_duration: "3s"
  leaderless_samples_threshold: 3

  self_healthy:
    minimum_duration: "5s"
    poll_interval_duration: "2s"

  active:
    command: "curl"
    args:
      - "-sf"
      - "-X"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "-d"
      - '{"action":"set_active","target":"{{ .SelfName }}","profile":"{{ .ProfileName }}"}'
      - "http://mock-solana:8899/action"

  passive:
    command: "curl"
    args:
      - "-sf"
      - "-X"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "-d"
      - '{"action":"set_passive","target":"{{ .SelfName }}","profile":"{{ .ProfileName }}"}'
      - "http://mock-solana:8899/action"

profiles:
  main:
    priority: 0
    identities:
      active_pubkey: "ArkzFExXXHaA6izkNhTJJ5zpXdQpynffjfRMJu4Yq6H"
    vote_pubkey: "ArkzFExXXHaA6izkNhTJJ5zpXdQpynffjfRMJu4Yq6H"
    authorized_voter: "ArkzFExXXHaA6izkNhTJJ5zpXdQpynffjfRMJu4Yq6H"
    peers:
      validator-1:
        ip: "10.0.0.100"
        priority: 0
      validator-2:
        ip: "10.0.0.101"
        priority: 1
      validator-3:
        ip: "10.0.0.102"
        priority: 2

  secondary:
    priority: 1
    identities:
      active_pubkey: "SysvarC1ock11111111111111111111111111111111"
    vote_pubkey: "SysvarC1ock11111111111111111111111111111111"
    authorized_voter: "SysvarRecentB1ockHashes11111111111111111111"
    peers:
      validator-3:
        ip: "10.0.0.102"
        priority: 0
      validator-2:
        ip: "10.0.0.101"
        priority: 1
      validator-1:
        ip: "10.0.0.100"
        priority: 2
